In [1]:
#检测cuda能用吗
import torch
print(torch.cuda.is_available())
print(torch.version.cuda) #查看cuda
print(torch.backends.cudnn.version()) #查看cudnn版本2.0.1
#查看pytorch版本
print(torch.__version__)

True
11.8
8700
2.1.0+cu118


In [2]:
import torch
print(torch.cuda.get_device_properties(1))  # 0 表示第一个GPU

_CudaDeviceProperties(name='NVIDIA GeForce RTX 3090', major=8, minor=6, total_memory=24259MB, multi_processor_count=82)


In [1]:
a = 85.88 + 72.34 + 72.21 + 63.87 + 66.92 + 55.76 + 37.75 + 54.10
a/8

63.603750000000005

In [1]:
import os
import cv2

# 指定图像文件夹路径
folder_path = 'data/uavid/test_val/images'

# 获取文件夹中所有图像文件的路径
image_paths = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith(('.jpg', '.png', '.jpeg'))]

# 遍历每张图像文件并输出尺寸
for image_path in image_paths:
    # 读取图像
    image = cv2.imread(image_path)
    
    if image is not None:
        # 获取图像尺寸
        height, width, channels = image.shape
        
        # 输出图像尺寸
        print(f"Image {image_path} size: {width} x {height}")
    else:
        print(f"Error reading image {image_path}")

Image data/uavid/test_val/images/seq41_000000_0_4.png size: 1024 x 1024
Image data/uavid/test_val/images/seq41_000400_0_4.png size: 1024 x 1024
Image data/uavid/test_val/images/seq41_000500_0_4.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000600_0_0.png size: 1024 x 1024
Image data/uavid/test_val/images/seq41_000700_0_4.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000300_0_0.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000900_0_4.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000700_0_0.png size: 1024 x 1024
Image data/uavid/test_val/images/seq41_000800_0_4.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000500_0_0.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000400_0_0.png size: 1024 x 1024
Image data/uavid/test_val/images/seq41_000100_0_0.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000100_0_0.png size: 1024 x 1024
Image data/uavid/test_val/images/seq23_000900_0_0.png size: 1024

In [5]:
import os
from PIL import Image

# 定义每组图像的大小和行列数
image_size = (1024, 1024)
rows = 2
columns = 4

# 定义文件夹路径
input_folder = "output/all/patch"
output_folder = "output/all/concat"

# 创建保存拼接图像的文件夹
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

def concat_images():
    # 初始化字典来存储每组图像的名称和路径
    image_groups = {}
    # 获取输入文件夹中的所有图像文件并进行排序
    image_files = sorted(os.listdir(input_folder))
    print(image_files)
    # 遍历图像文件列表并将图像按组存储到字典中
    for image_file in image_files:
        image_name = image_file.split("_")[0]+image_file.split("_")[1]
        if image_name not in image_groups:
            image_groups[image_name] = []
        image_path = os.path.join(input_folder, image_file)
        image_groups[image_name].append(image_path)
    return image_groups


# 定义函数来拼接图像
def concatenate_images(image_paths):
    # 创建一个空白画布来存放拼接后的图像
    concat_image = Image.new("L", (columns * image_size[0], rows * image_size[1]))
    
    # 遍历每张图像的路径和对应的行列位置并进行拼接
    for i, image_path in enumerate(image_paths):
        row = i // columns
        column = i % columns
        image = Image.open(image_path)
        concat_image.paste(image, (column * image_size[0], row * image_size[1]))
    
    return concat_image


image_groups = concat_images()
for image_name, image_paths in image_groups.items():
    print(image_name,image_paths)
#     concat_image = concatenate_images(image_paths)
#     output_name = image_name + ".png"
#     output_path = os.path.join(output_folder, output_name)
#     concat_image.save(output_path)
# print("图像拼接完成！")

['seq22_000900_0_0.png', 'seq22_000900_0_1.png', 'seq22_000900_0_2.png', 'seq22_000900_0_3.png', 'seq22_000900_0_4.png', 'seq22_000900_0_5.png', 'seq22_000900_0_6.png', 'seq22_000900_0_7.png', 'seq30_000900_0_0.png', 'seq30_000900_0_1.png', 'seq30_000900_0_2.png', 'seq30_000900_0_3.png', 'seq30_000900_0_4.png', 'seq30_000900_0_5.png', 'seq30_000900_0_6.png', 'seq30_000900_0_7.png']
seq22000900 ['output/all/patch/seq22_000900_0_0.png', 'output/all/patch/seq22_000900_0_1.png', 'output/all/patch/seq22_000900_0_2.png', 'output/all/patch/seq22_000900_0_3.png', 'output/all/patch/seq22_000900_0_4.png', 'output/all/patch/seq22_000900_0_5.png', 'output/all/patch/seq22_000900_0_6.png', 'output/all/patch/seq22_000900_0_7.png']
seq30000900 ['output/all/patch/seq30_000900_0_0.png', 'output/all/patch/seq30_000900_0_1.png', 'output/all/patch/seq30_000900_0_2.png', 'output/all/patch/seq30_000900_0_3.png', 'output/all/patch/seq30_000900_0_4.png', 'output/all/patch/seq30_000900_0_5.png', 'output/all/pat

In [6]:
from PIL import Image
import numpy as np

# 打开图像文件
img = Image.open('output/all/patch/seq30_000900_0_3.png')

# 将图像转换为NumPy数组
img_array = np.array(img)

# 打印数组
print(img_array)

[[[128   0   0]
  [128   0   0]
  [128   0   0]
  ...
  [  0 128   0]
  [  0 128   0]
  [  0 128   0]]

 [[128   0   0]
  [128   0   0]
  [128   0   0]
  ...
  [  0 128   0]
  [  0 128   0]
  [  0 128   0]]

 [[128   0   0]
  [128   0   0]
  [128   0   0]
  ...
  [  0 128   0]
  [  0 128   0]
  [  0 128   0]]

 ...

 [[128  64 128]
  [128  64 128]
  [128  64 128]
  ...
  [128   0   0]
  [128   0   0]
  [128   0   0]]

 [[128  64 128]
  [128  64 128]
  [128  64 128]
  ...
  [128   0   0]
  [128   0   0]
  [128   0   0]]

 [[128  64 128]
  [128  64 128]
  [128  64 128]
  ...
  [128   0   0]
  [128   0   0]
  [128   0   0]]]


In [2]:
import numpy as np
import torch
from torch import nn
from torch.nn import init
from torch.nn.parameter import Parameter

class ChannelAttentionModule(nn.Module):
    def __init__(self, in_channels, reduction=4):
        super(ChannelAttentionModule, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.fc = nn.Sequential(
            nn.Conv2d(in_channels, in_channels // reduction, 1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv2d(in_channels // reduction, in_channels, 1, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = self.fc(self.avg_pool(x))
        max_out = self.fc(self.max_pool(x))
        out = avg_out + max_out
        return self.sigmoid(out)

class SpatialAttentionModule(nn.Module):
    def __init__(self, kernel_size=7):
        super(SpatialAttentionModule, self).__init__()
        self.conv1 = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x = torch.cat([avg_out, max_out], dim=1)
        x = self.conv1(x)
        return self.sigmoid(x)

# 输入 N C H W,  输出 N C H W
if __name__ == '__main__':
    input = torch.randn(50, 512, 7, 7)
    se = ChannelAttentionModule(in_channels=512)
    output = se(input)
    print(output.shape)

torch.Size([50, 512, 1, 1])


In [9]:
input = torch.randn(50, 512, 1, 1)
se = SpatialAttentionModule()
output = se(input)
print(output.shape)

torch.Size([50, 1, 1, 1])


In [21]:
import torch.nn.functional as F

class ShuffleAttention(nn.Module):
    # 初始化Shuffle Attention模块
    def __init__(self, channel=512, reduction=16, G=8):
        super().__init__()
        self.G = G  # 分组数量
        self.channel = channel  # 通道数
        self.avg_pool = nn.AdaptiveAvgPool2d(1)  # 全局平均池化，用于生成通道注意力
        self.gn = nn.GroupNorm(channel // (2 * G), channel // (2 * G))  # 分组归一化，用于空间注意力
        # 以下为通道注意力和空间注意力的权重和偏置参数
        self.cweight = Parameter(torch.zeros(1, channel // (2 * G), 1, 1))
        self.cbias = Parameter(torch.ones(1, channel // (2 * G), 1, 1))
        self.sweight = Parameter(torch.zeros(1, channel // (2 * G), 1, 1))
        self.sbias = Parameter(torch.ones(1, channel // (2 * G), 1, 1))
        self.sigmoid = nn.Sigmoid()  # Sigmoid函数，用于生成注意力图
        self.fc = nn.Linear(channel, 1)  # 添加全连接层将通道数从512减少到1


    # 权重初始化方法
    def init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                init.kaiming_normal_(m.weight, mode='fan_out')
                if m.bias is not None:
                    init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                init.constant_(m.weight, 1)
                init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                init.normal_(m.weight, std=0.001)
                if m.bias is not None:
                    init.constant_(m.bias, 0)

    # 通道混洗方法，用于在分组处理后重组特征
    @staticmethod
    def channel_shuffle(x, groups):
        b, c, h, w = x.shape
        x = x.reshape(b, groups, -1, h, w)
        x = x.permute(0, 2, 1, 3, 4)
        x = x.reshape(b, -1, h, w)
        return x

    # 前向传播方法
    def forward(self, x):
        b, c, h, w = x.size()
        x = x.view(b * self.G, -1, h, w)  # 将输入特征图按照分组维度进行重排

        x_0, x_1 = x.chunk(2, dim=1)  # 将特征图分为两部分，分别用于通道注意力和空间注意力

        # 通道注意力分支
        x_channel = self.avg_pool(x_0)  # 对第一部分应用全局平均池化
        x_channel = self.cweight * x_channel + self.cbias  # 应用学习到的权重和偏置
        x_channel = x_0 * self.sigmoid(x_channel)  # 通过sigmoid激活函数和原始特征图相乘，得到加权的特征图

        # 空间注意力分支
        x_spatial = self.gn(x_1)  # 对第二部分应用分组归一化
        x_spatial = self.sweight * x_spatial + self.sbias  # 应用学习到的权重和偏置
        x_spatial = x_1 * self.sigmoid(x_spatial)  # 通过sigmoid激活函数和原始特征图相乘，得到加权的特征图

        # 将通道注意力和空间注意力的结果沿通道维度拼接
        out = torch.cat([x_channel, x_spatial], dim=1)
        out = out.contiguous().view(b, -1, h, w)  # 重新调整形状以匹配原始输入的维度

        # 应用通道混洗，以便不同分组间的特征可以交换信息
        out = self.channel_shuffle(out, 2)

        # 应用全连接层将通道数从512减少到1
        out = self.fc(out)
        out = out.view(b, 1, 1, 1)
        
        return out


# 输入 N C H W,  输出 N C H W
if __name__ == '__main__':
    input = torch.randn(50, 512, 7, 7)
    se = ShuffleAttention(channel=512, G=4)
    output = se(input)
    print(output.shape)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (179200x7 and 512x1)

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 定义h_sigmoid激活函数，这是一种硬Sigmoid函数
class h_sigmoid(nn.Module):
    def __init__(self, inplace=True):
        super(h_sigmoid, self).__init__()
        self.relu = nn.ReLU6(inplace=inplace)  # 使用ReLU6实现

    def forward(self, x):
        return self.relu(x + 3) / 6  # 公式为ReLU6(x+3)/6，模拟Sigmoid激活函数

# 定义h_swish激活函数，这是基于h_sigmoid的Swish函数变体
class h_swish(nn.Module):
    def __init__(self, inplace=True):
        super(h_swish, self).__init__()
        self.sigmoid = h_sigmoid(inplace=inplace)  # 使用上面定义的h_sigmoid

    def forward(self, x):
        return x * self.sigmoid(x)  # 公式为x * h_sigmoid(x)

# 定义Coordinate Attention模块
class CoordAtt(nn.Module):
    def __init__(self, inp, oup, reduction=32):
        super(CoordAtt, self).__init__()
        # 定义水平和垂直方向的自适应平均池化
        self.pool_h = nn.AdaptiveAvgPool2d((None, 1))  # 水平方向
        self.pool_w = nn.AdaptiveAvgPool2d((1, None))  # 垂直方向

        mip = max(8, inp // reduction)  # 计算中间层的通道数

        # 1x1卷积用于降维
        self.conv1 = nn.Conv2d(inp, mip, kernel_size=1, stride=1, padding=0)
        self.bn1 = nn.BatchNorm2d(mip)  # 批归一化
        self.act = h_swish()  # 激活函数

        # 两个1x1卷积，分别对应水平和垂直方向
        self.conv_h = nn.Conv2d(mip, oup, kernel_size=1, stride=1, padding=0)
        self.conv_w = nn.Conv2d(mip, oup, kernel_size=1, stride=1, padding=0)

    def forward(self, x):
        identity = x  # 保存输入作为残差连接

        n, c, h, w = x.size()  # 获取输入的尺寸
        x_h = self.pool_h(x)  # 水平方向池化
        x_w = self.pool_w(x).permute(0, 1, 3, 2)  # 垂直方向池化并交换维度以适应拼接

        y = torch.cat([x_h, x_w], dim=2)  # 拼接水平和垂直方向的特征
        y = self.conv1(y)  # 通过1x1卷积降维
        y = self.bn1(y)  # 批归一化
        y = self.act(y)  # 激活函数

        x_h, x_w = torch.split(y, [h, w], dim=2)  # 将特征拆分回水平和垂直方向
        x_w = x_w.permute(0, 1, 3, 2)  # 恢复x_w的原始维度

        a_h = self.conv_h(x_h).sigmoid()  # 通过1x1卷积并应用Sigmoid获取水平方向的注意力权重
        a_w = self.conv_w(x_w).sigmoid()  # 通过1x1卷积并应用Sigmoid获取垂直方向的注意力权重

        out = identity * a_w * a_h  # 应用注意力权重到输入特征，并与残差连接相乘

        return out  # 返回输出

# 示例使用
if __name__ == '__main__':

    input = torch.randn(50, 512, 7, 7)  # 创建一个随机输入
    block = CoordAtt(input.shape[2], input.shape[3])  # 实例化Coordinate Attention模块
    output = block(input)  # 通过模块处理输入
    print(output.shape)  # 打印输入和输出的尺寸


RuntimeError: Given groups=1, weight of size [8, 7, 1, 1], expected input[50, 512, 14, 1] to have 7 channels, but got 512 channels instead

In [24]:
input = torch.randn(50, 512, 7, 7)  # 创建一个随机输入

7